server:
  port: 8060
  servlet:
    context-path: /seat

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: seat
    password: Seat_12345
    url: jdbc:mysql://152.136.68.54:3306/server_seat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8


#  mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/**/*Mapper.xml

  # 打印sql
logging:
  level:
    com.example.seating.mapper: debug

